[workspace]
members = ["backend/libs/*", "backend/bin", "backend/bindings_generator"]
resolver = "2"

[profile.release]
strip = true

[profile.release-small]
inherits = "release"
opt-level = "z"
lto = true
panic = 'abort'
codegen-units = 1
