[package]
name = "radcam-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
default-run = "radcam-manager"

[dependencies]
autopilot = { path="../libs/autopilot" }
mcm_client = { path="../libs/mcm_client" }
radcam_manager = { path="../libs/radcam_manager" }
settings = { path="../libs/settings" }
web_client = { path="../libs/web_client" }

anyhow = { workspace = true }
chrono = { workspace = true }
clap = { version = "4.5.26", features = ["derive"] }
once_cell = { workspace = true }
shellexpand = "3.1.1"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[build-dependencies]
vergen-gix = { version = "1.0.9", default-features = false, features = ["build", "cargo"] }