name: Deploy BlueOS Extension Image

on:
  push:
  # Run manually
  workflow_dispatch:
  # NOTE: caches may be removed if not run weekly
  #  -> may be worth scheduling for every 6 days

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "${{ hashFiles('**/Cargo.lock') }}"
          shared-key: "shared"
      
      - name: Install build dependencies - Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl,armv7-unknown-linux-musleabihf
        
      - name: Install build dependencies - Cross
        run: cargo install cross

      - name: Install build dependencies - NPM
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache-dependency-path: 'frontend/package-lock.json'
          cache: 'npm'

      - name: Cross-build
        run: ./build_cross.sh --verbose

      - name: Upload aarch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: radcam-manager-aarch64
          path: target/build/aarch64-unknown-linux-musl/aarch64-unknown-linux-musl/release/radcam-manager

      - name: Upload armv7 binary
        uses: actions/upload-artifact@v4
        with:
          name: radcam-manager-armv7
          path: target/build/armv7-unknown-linux-musleabihf/armv7-unknown-linux-musleabihf/release/radcam-manager

      - name: Upload x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: radcam-manager-x86_64
          path: target/build/x86_64-unknown-linux-musl/x86_64-unknown-linux-musl/release/radcam-manager

      - name: Upload aarch64 to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/build/aarch64-unknown-linux-musl/aarch64-unknown-linux-musl/release/radcam-manager
          asset_name: radcam-manager-aarch64
          tag: ${{ github.ref }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          overwrite: true

      - name: Upload armv7 to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/build/armv7-unknown-linux-musleabihf/armv7-unknown-linux-musleabihf/release/radcam-manager
          asset_name: radcam-manager-armv7
          tag: ${{ github.ref }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          overwrite: true

      - name: Upload x86_64 to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/build/x86_64-unknown-linux-musl/x86_64-unknown-linux-musl/release/radcam-manager
          asset_name: radcam-manager-x86_64
          tag: ${{ github.ref }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          overwrite: true

      - name: Deploy BlueOS Extension
        uses: joaoantoniocardoso/Deploy-BlueOS-Extension@allow-dirty
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: 'radcam-manager'
          checkout-clean: false